# Use the official Nginx image.
FROM nginx:alpine

# Remove the default Nginx configuration file.
RUN rm /etc/nginx/conf.d/default.conf

# Add our Nginx configuration file.
COPY nginx.conf /etc/nginx/conf.d/
